### ISSUE TITLE
ImportError: No module named 'utilities'

### ISSUE THREAD

**Issue by bodono** [cvxgrp/qcqp#1]
=> pip install --upgrade cvxpy
=> pip install qcqp

download maxcut.py to new directory

=> python maxcut.py 
Traceback (most recent call last):
  File "maxcut.py", line 4, in <module>
    import qcqp
  File "/usr/local/google/home/bodonoghue/miniconda2/envs/python35/lib/python3.5/site-packages/qcqp/__init__.py", line 20, in <module>
    from . import qcqp_problem
  File "/usr/local/google/home/bodonoghue/miniconda2/envs/python35/lib/python3.5/site-packages/qcqp/qcqp_problem.py", line 30, in <module>
    from utilities import *
ImportError: No module named 'utilities'

Running ubuntu, python 3.5.

**Comment by jaehyunp** [comment]
I'll take a look a this today. Meanwhile, could you tell me if downloading and installing the package directly from the repository also gives the same error?

**Comment by bodono** [comment]
Works fine when installing from source.

**Comment by jaehyunp** [comment]
Thanks, just uploaded a new version of the package (0.5) on pip. It should be fixed now.
