### ISSUE TITLE
use without Mosek solver - example testing

### ISSUE THREAD

**Issue by AIAdventures** [cvxgrp/qcqp#2]
andrewcz@andrewcz-PORTEGE-Z30t-B ~/qcqp/examples $ python maxcut.py 
/home/andrewcz/miniconda3/lib/python3.5/site-packages/cvxpy/atoms/quad_form.py:81: UserWarning: Forming a nonconvex expression quad_form(x, indefinite).
  warnings.warn("Forming a nonconvex expression quad_form(x, indefinite).")
Traceback (most recent call last):
  File "maxcut.py", line 25, in <module>
    qcqp.suggest(SDR, solver=cvx.MOSEK)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/qcqp-0.7-py3.5.egg/qcqp/qcqp.py", line 346, in suggest
    self.sdr_sol, self.sdr_bound = solve_sdr(self.qcqp_form, *args, **kwargs)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/qcqp-0.7-py3.5.egg/qcqp/qcqp.py", line 89, in solve_sdr
    rel_prob.solve(*args, **kwargs)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 209, in solve
    return self._solve(*args, **kwargs)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/cvxpy/problems/problem.py", line 331, in _solve
    kwargs)
  File "/home/andrewcz/miniconda3/lib/python3.5/site-packages/cvxpy/problems/solvers/mosek_intf.py", line 239, in solve
    task.optimize()
  File "/home/andrewcz/.local/lib/python3.5/site-packages/mosek/__init__.py", line 127, in accept
    return fun(*[ t(a) for (t,a) in zip(argtlst,args) ])
  File "/home/andrewcz/.local/lib/python3.5/site-packages/mosek/__init__.py", line 7430, in optimize
    raise Error(rescode(res),Env.getcodedesc(rescode(res))[1])
mosek.Error: (1008) A license cannot be located.

Hi apologies is there any way to use package with out the mosek solver.
Many thanks,
Andrew

**Comment by jaehyunp** [comment]
Hi Andrew,

Thanks for pointing this out. The MOSEK solver was specified for testing purposes, but QCQP can be executed without it, by simply calling the ``suggest()`` method without the ``solver`` argument: ``qcqp.suggest(SDR)``. We have updated our documentation and sample codes accordingly. Please clone the latest version of the repository and try again.

**Comment by AIAdventures** [comment]
Thank you!
Amazing package 😃.
Best,
Andrew
